name: Build and push golang container image to google container registry

on: [push]
  #push:
    # Pattern matched against refs/tags
  #  tags:        
  #    - '*'
jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: looks-api
      PROJECT_ID: the-wap-377118
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env version from tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-southwest1-docker.pkg.dev --quiet
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v1.0.0-beta.1
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$RELEASE_VERSION
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$RELEASE_VERSION

        